# docker compose --env-file .env.docker.dev -f docker-compose.dev.yml up --build --watch


name: drawith-dev

services:
  postgres:
    image: postgres:16-alpine
    container_name: drawith-postgres-dev
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: drawith-app-dev
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - node_modules/
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync
          path: ./lib
          target: /app/lib
          ignore:
            - node_modules/
        - action: sync
          path: ./public
          target: /app/public
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  postgres_data:
